# from tkinter import *
# from tkinter import ttk
# master =Tk()
# ttk.Button(master, text='Title').grid(row=0)
# ttk.Button(master, text='First Name').grid(row=1)
# ttk.Button(master, text='Last Name').grid(row=2)
# ttk.Button(master, text='Email').grid(row=3)
# ttk.Button(master, text='Enterprise id').grid(row=4)
# ttk.Button(master, text='Project name').grid(row=5)
# ttk.Button(master, text='Technology').grid(row=6)
# ttk.Button(master, text='Manager').grid(row=7)
# ttk.Button(master, text='Locations').grid(row=8)
# e1 = Entry(master)
# e2 = Entry(master)
# e3 = Entry(master)
# e4 = Entry(master)
# e5 = Entry(master)
# e6 = Entry(master)
# e7 = Entry(master)
# e8 = Entry(master)
# e9 = Entry(master)
# e1.grid(row=0, column=1)
# e2.grid(row=1, column=1)
# e3.grid(row=2, column=1)
# e4.grid(row=3, column=1)
# e5.grid(row=4, column=1)
# e6.grid(row=5, column=1)
# e7.grid(row=6, column=1)
# e8.grid(row=7, column=1)
# e9.grid(row=8, column=1)

# ttk.Button(master, text="SUBMIT").grid(row=9)
# mainloop()